apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
type: Opaque
data:
  EventHubConnectionString: {{ default "" .Values.secrets.ehconnstring | b64enc | quote }}
  EventHubName: {{ default "" .Values.secrets.ehname | b64enc | quote }}